apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the ReplicaSet instance
  name: mongodb
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      # Run the nginx image
      - name: mongodb
        image: mongo:3.6.5-jessie
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db

      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  ports:
    - name: http
      port: 27017

  selector:
    app: mongodb
  type: ClusterIP

